"""create car model

Revision ID: f78aaef83dac
Revises: 
Create Date: 2025-12-19 11:50:18.845242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78aaef83dac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('images_count', sa.Integer(), nullable=False),
    sa.Column('car_number', sa.String(length=20), nullable=False),
    sa.Column('car_vin', sa.String(length=50), nullable=False),
    sa.Column('datetime_found', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
